---
- name: Check existence of Wallabag systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wallabag_identifier }}.service"
  register: wallabag_service_stat

- when: wallabag_service_stat.stat.exists | bool
  block:
    - name: Ensure Wallabag systemd service is stopped
      ansible.builtin.service:
        name: "{{ wallabag_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Wallabag systemd service does not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wallabag_identifier }}.service"
        state: absent

    - name: Ensure Wallabag path doesn't exist
      ansible.builtin.file:
        path: "{{ wallabag_base_path }}"
        state: absent
